// This file is generated by testgen to include all files in the lib directory
// for coverage collection purposes, Don't modify or delete this file.
import 'package:my_web_app/main.dart';
import 'package:my_web_app/counter_cubit.dart';

void main(){}
