// This file is generated by testgen to include all files in the lib directory
// for coverage collection purposes, Don't modify or delete this file.
import 'package:test_gen_ai/calculator.dart';
import 'package:test_gen_ai/src/coverage/coverage_collection.dart';
import 'package:test_gen_ai/src/coverage/utils.dart';
import 'package:test_gen_ai/src/analyzer/extractor.dart';
import 'package:test_gen_ai/src/analyzer/parser.dart';
import 'package:test_gen_ai/src/analyzer/visitor.dart';
import 'package:test_gen_ai/src/analyzer/declaration.dart';
import 'package:test_gen_ai/flutter_testgen.dart';

void main(){}
